### ISSUE TITLE
assign() bug

### ISSUE THREAD

**Issue by csanda87** [dollarshaveclub/study#27]
Hello,

When calling study.assign(testName) the control always goes into the store.  No matter what weight you specify or how many times you reload.

I took the following steps:
-mkdir test
-npm init
-npm i studyjs --save

You can reproduce this by using the code in the readme.

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<script src="node_modules/studyjs/build/study.js"></script>
	<script>
		// Set up our test API
		  const test = new Study({
		    store: Study.stores.local
		  });

		  // Define a test
		  test.define({
		    name: 'new-homepage',
		    buckets: {
		      control: { weight: 0.6 },
		      versionA: { weight: 0.2 },
		      versionB: { weight: 0.2 },
		    }
		  });

		  // Bucket the user
		  test.assign('new-homepage');
	</script>
</body>
</html>

console.log(localStorage.getItem('ab-tests')) // returns "{"new-homepage":"control"}"

```
study.assign(testName) returns control 100% of the time

**Comment by briangonzalez** [comment]
@csanda87 Thanks for the reports. Mind making a codepen or jsfiddle?

**Comment by jakiestfu** [comment]
The source of the issue lives here: https://github.com/dollarshaveclub/study/blob/master/src/study.js#L156

We should not be calling `getDefaultBucket`, rather, we should actually choose a weighted item.
