### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by PeterCadwell** [dollarshaveclub/study#4]
Started seeing a Mixed Content error.

Can the protocol change to secure?
Instead of this: **http://i.imgur.com/lnDx7VT.jpg**
Use this: **https://i.imgur.com/lnDx7VT.jpg**

**Comment by yowainwright** [comment]
@PeterCadwell how 'bout givin' ya boy a 🌟

Can we do?
```
//i.imgur.com/lnDx7VT.jpg
```

**Comment by jakiestfu** [comment]
We don't have a built in interface for study anymore, fellas. Expect that logic to live as a separate repo 🙏
